### ISSUE TITLE
盡量不要有全域變數

### ISSUE THREAD

**Issue by azole** [krugerliu/node-mfee16-krugerliu#1]
https://github.com/krugerliu/node-mfee16-krugerliu/blob/a4bcb91cf72a57ee5fc5eaeb93233353c636379c/sum.js#L9

這裡如果沒有加上 let 會讓 i 變成全域變數

for (`let` i = 1; i <= p1; i++) {

**Comment by krugerliu** [comment]
己修正, 感謝老師提醒 !
