### ISSUE TITLE
onload 的 input

### ISSUE THREAD

**Issue by azole** [krugerliu/node-mfee16-krugerliu#2]
https://github.com/krugerliu/node-mfee16-krugerliu/blob/6cc30e6591ce5c1df9e47e6c3373a7ad6ef083fd/basic/index.html#L29

onload 應該是沒有 response 這個 input，就是用 this.responseText 就可以了，你可以 console.log(this) 觀察看看。

**Comment by krugerliu** [comment]
已修正並上傳, 感謝老師的提醒
